apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-db-init
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "{{ if .Values.hooks.removeOnSuccess }}hook-succeeded,{{ end }}before-hook-creation"
    "helm.sh/hook-weight": "6"
spec:
  {{- if .Values.hooks.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ .Values.hooks.activeDeadlineSeconds }}
  {{- end}}
  template:
    metadata:
      name: {{ template "fullname" . }}-db-init
      annotations:
        checksum/configmap.yaml: {{ include (print $.Template.BasePath "/configmap-sentry.yaml") . | sha256sum }}
      labels:
        app: sentry
        release: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
      - name: db-init-job
        image: "{{required ".Values.global.registry is missing" .Values.global.registry }}/{{ .Values.image.sentry.repository }}:{{required ".Values.image.sentry.tag is missing" .Values.image.sentry.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.sentry.pullPolicy }}
        command: ["sentry","upgrade","--noinput"]
        env:
{{ include "env-vars" . | indent 8 }}
