kind: Service
apiVersion: v1

metadata:
  name: {{ include "fullName" . }}
  namespace:  {{.Release.Namespace}}
  labels:
    system: openstack
    type: database
    component: {{.Values.name}}
  annotations:
spec:
  type: ClusterIP
  selector:
    app: {{ include "fullName" . }}
  ports:
    - name: {{ include "fullName" . }}
      port: {{.Values.port_public}}
{{- if or .Values.backup_v2.enabled .Values.readiness.useSidecar }}
    - name: readiness
      port: 8080
{{- end }}

{{- if .Values.backup_v2.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullName" . }}-backup
  labels:
    app: {{ include "fullName" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{- if and $.Values.global.linkerd_enabled $.Values.global.linkerd_requested }}
    linkerd.io/inject: enabled
{{- end }}
spec:
  selector:
    app: {{ include "fullName" . }}-backup
  ports:
    - port: 8081
      name: http
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 8082
      protocol: TCP
{{- end }}
