apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-relay
  labels:
    app: {{ template "fullname" . }}-relay
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "25"
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-relay
      release: "{{ .Release.Name }}"
      role: relay
{{- if not .Values.relay.autoscaling.enabled }}
  replicas: {{ .Values.relay.replicas }}
{{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      annotations:
        checksum/relay: {{ .Values.config.relay | sha256sum }}
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-relay.yaml") . | sha256sum }}
        {{- if .Values.relay.annotations }}
{{ toYaml .Values.relay.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "fullname" . }}-relay
        release: "{{ .Release.Name }}"
        role: relay
        {{- if .Values.relay.podLabels }}
{{ toYaml .Values.relay.podLabels | indent 8 }}
        {{- end }}
    spec:
      initContainers:
        - name: {{ .Chart.Name }}-relay-init
          image: "{{required ".Values.global.dockerHubMirror is missing" .Values.global.dockerHubMirror }}/{{ required ".Values.image.relay.repository is missing" .Values.image.relay.repository }}:{{ required ".Values.image.relay.tag is missing" .Values.image.relay.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.relay.pullPolicy }}
          args:
            - "credentials"
            - "generate"
          env:
            - name: RELAY_PORT
              value: '{{ template "relay.port" }}'
          volumeMounts:
            - name: credentials
              mountPath: /work/.relay
            - name: config
              mountPath: /work/.relay/config.yml
              subPath: config.yml
              readOnly: true
      containers:
      - name: {{ .Chart.Name }}-relay
{{- if .Values.relay.args }}
        args:
{{ toYaml .Values.relay.args | indent 10 }}
{{- end }}
        image: "{{required ".Values.global.dockerHubMirror is missing" .Values.global.dockerHubMirror }}/{{ required ".Values.image.relay.repository is missing" .Values.image.relay.repository }}:{{ required ".Values.image.relay.tag is missing" .Values.image.relay.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.sentry.pullPolicy }}
        ports:
        - containerPort: {{ template "relay.port" }}
        env:
        - name: RELAY_PORT
          value: '{{ template "relay.port" }}'
        volumeMounts:
          - name: credentials
            mountPath: /work/.relay
          - name: config
            mountPath: /work/.relay/config.yml
            subPath: config.yml
            readOnly: true
{{- if .Values.relay.volumeMounts }}
{{ toYaml .Values.relay.volumeMounts | indent 10 }}
{{- end }}
        livenessProbe:
          failureThreshold: {{ .Values.relay.probeFailureThreshold }}
          httpGet:
            path: {{ template "relay.healthCheck.livenessRequestPath" }}
            port: {{ template "relay.port" }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.relay.probeInitialDelaySeconds }}
          periodSeconds: {{ .Values.relay.probePeriodSeconds }}
          successThreshold: {{ .Values.relay.probeSuccessThreshold }}
          timeoutSeconds: {{ .Values.relay.probeTimeoutSeconds }}
        readinessProbe:
          failureThreshold: {{ .Values.relay.probeFailureThreshold }}
          httpGet:
            path: {{ template "relay.healthCheck.readinessRequestPath" }}
            port: {{ template "relay.port" }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.relay.probeInitialDelaySeconds }}
          periodSeconds: {{ .Values.relay.probePeriodSeconds }}
          successThreshold: {{ .Values.relay.probeSuccessThreshold }}
          timeoutSeconds: {{ .Values.relay.probeTimeoutSeconds }}
        resources:
{{ toYaml .Values.relay.resources | indent 12 }}
{{- if .Values.relay.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.relay.containerSecurityContext | indent 12 }}
{{- end }}
{{- if .Values.relay.sidecars }}
{{ toYaml .Values.relay.sidecars | indent 6 }}
{{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-relay
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "fullname" . }}-relay
          defaultMode: 0644
      - name: credentials
        emptyDir: {}
