apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-post-process-forward-issue-platform
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "10"
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
        app: sentry
        release: "{{ .Release.Name }}"
        role: sentry-post-process-forward-issue-platform
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/configYml: {{ .Values.config.configYml | toYaml | toString | sha256sum }}
        checksum/sentryConfPy: {{ .Values.config.sentryConfPy | sha256sum }}
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-sentry.yaml") . | sha256sum }}
      labels:
        app: sentry
        release: "{{ .Release.Name }}"
        role: sentry-post-process-forward-issue-platform
    spec:
      containers:
      - name: {{ .Chart.Name }}-post-process-forward-issue-platform
        image: "{{required ".Values.global.registry is missing" .Values.global.registry }}/{{ .Values.image.sentry.repository }}:{{required ".Values.image.sentry.tag is missing" .Values.image.sentry.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.sentry.pullPolicy }}
        command: ["sentry"]
        args:
          - "run"
          - "consumer"
          - "post-process-forwarder-issue-platform"
          - "--consumer-group"
          - "post-process-forwarder"
          - "--synchronize-commit-log-topic=snuba-generic-events-commit-log"
          - "--synchronize-commit-group"
          - "generic_events_group"
        env:
{{ include "env-vars" . | indent 8 }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-post-process-forwarder-issue-platform
      {{- end }}
