{{- if .Values.sentry.features.enableProfiling }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-ingest-profiles
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "10"
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      release: "{{ .Release.Name }}"
      role: ingest-profiles
{{- if not .Values.sentry.ingestProfiles.autoscaling.enabled }}
  replicas: {{ .Values.sentry.ingestProfiles.replicas }}
{{- end }}
  template:
    metadata:
      annotations:
        checksum/configYml: {{ .Values.config.configYml | toYaml | toString | sha256sum }}
        checksum/sentryConfPy: {{ .Values.config.sentryConfPy | sha256sum }}
        # checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-sentry.yaml") . | sha256sum }}
        {{- if .Values.sentry.ingestProfiles.annotations }}
{{ toYaml .Values.sentry.ingestProfiles.annotations | indent 8 }}
        {{- end }}
    spec:
      labels:
        app: {{ template "fullname" . }}
        release: "{{ .Release.Name }}"
        role: ingest-profiles
        {{- if .Values.sentry.ingestProfiles.podLabels }}
{{ toYaml .Values.sentry.ingestProfiles.podLabels | indent 8 }}
        {{- end }}
      containers:
      - name: {{ .Chart.Name }}-ingest-profiles
        image: "{{required ".Values.global.registry is missing" .Values.global.registry }}/{{ .Values.image.sentry.repository }}:{{required ".Values.image.sentry.tag is missing" .Values.image.sentry.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.sentry.pullPolicy }}
        command: ["sentry"]
        args:
          - "run"
          - "ingest-profiles"
        env:
        - name: C_FORCE_ROOT
          value: "true"
{{ include "env-vars" . | indent 8 }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-ingest-profiles
      {{- end }}
{{- end }}
