---
global:
  linkerd_requested: true

image:
  override: null
  name: percona/percona-xtradb-cluster-operator
  tag: 1.15.0
  pullPolicy: IfNotPresent

watchNamespace: ""
# watchNamespace: "monsoon3,monsoon3global"

disableTelemetry: true

logStructured: true

logLevel: "INFO"

extraEnvVars:
  - name: CC_FIX_PERMISSIONS
    value: true

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - preference:
        matchExpressions:
        - key: cloud.sap/maintenance-state
          operator: In
          values:
          - operational
      weight: 1
    - preference:
        matchExpressions:
        - key: cloud.sap/deployment-state
          operator: NotIn
          values:
          - reinstalling
      weight: 1

resources:
  limits:
    cpu: 2000m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 20Mi

owner-info:
  support-group: network-api
  maintainers:
    - Vladislav Gusev
    - Bashar Alkhateeb
    - Birk Bohne
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/system/pxc-operator
