apiVersion: v1
kind: Service
metadata:
  name: ipxe-http
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: ipxe
    port: 8082
    protocol: TCP
    targetPort: 8082
    nodePort: {{ .Values.ipxe.port }}
  selector:
    app.kubernetes.io/name: ipxe-operator
  type: NodePort
