{{- if .Values.config.monitoring.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: calico-bird-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    prometheus: kubernetes
spec:
  selector:
    matchLabels:
      monitoring: calico-bird
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: metrics-bird
    relabelings:
    - sourceLabels:
      - __meta_kubernetes_endpoint_node_name
      targetLabel: node
{{- end }}
