apiVersion: batch/v1
kind: Job
metadata:
  # since this name changes with every image change, removal and creation of
  # this Job happens on nearly every deployment. Check the helm-chart changes
  # to see if this needs more review.
  name: {{ tuple . "db-online-migrate" | include "job_name" }}
  labels:
    system: openstack
    type: configuration
    component: {{ .Chart.Name }}
spec:
  template:
    metadata:
      labels:
        alert-tier: os
        alert-service: {{ .Chart.Name }}
{{ tuple . .Release.Name "db-online-migrate" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        {{- include "utils.linkerd.pod_and_service_annotation" . | indent 8 }}
    spec:
      restartPolicy: OnFailure
      {{- include "utils.proxysql.job_pod_settings" . | indent 6 }}
      initContainers:
      {{- tuple . (dict "service" (include "db_name" .) "jobs" (tuple . "db-migrate" | include "job_name") ) | include "utils.snippets.kubernetes_entrypoint_init_container" | indent 6 }}
      containers:
      - name: db-online-migrate
        image: {{ required ".Values.global.registry is missing" .Values.global.registry}}/loci-masakari:{{.Values.imageVersion | required "Please set .imageVersion or similar" }}
        imagePullPolicy: IfNotPresent
        command:
        - dumb-init
        - bash
        - -c
        - |
          set -euo pipefail
          if which masakari-manage; then
              # masakari-manage db online_data_migrations # invalid argument ???
              #   usage: masakari-manage db [-h] {purge,sync,version} ...
              masakari-manage db version
          else
              # wait for proxysql to start so we can properly kill it
              sleep 5
          fi
          {{- include "utils.script.job_finished_hook" . | nindent 10 }}
        env:
          {{- if .Values.sentry.enabled }}
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry
              key: {{ .Chart.Name }}.DSN.python
          {{- end }}
        - name: PYTHONWARNINGS
          value: {{ .Values.python_warnings | quote }}
        volumeMounts:
        - mountPath: /etc/masakari
          name: masakari-etc
        - mountPath: /etc/masakari/masakari.conf.d
          name: masakari-etc-confd
        {{- include "utils.proxysql.volume_mount" . | indent 8 }}
        {{- include "utils.trust_bundle.volume_mount" . | indent 8 }}
      {{- include "utils.proxysql.container" . | indent 6 }}
      volumes:
      - name: masakari-etc
        configMap:
          name: masakari-etc
      - name: masakari-etc-confd
        secret:
          secretName: masakari-etc
      {{- include "utils.proxysql.volumes" . | indent 6 }}
      {{- include "utils.trust_bundle.volumes" . | indent 6 }}
