apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-etc
  labels:
    system: openstack
    type: configuration
    component: {{ .Chart.Name }}
type: Opaque
data: 
  secrets.conf: |
    {{ include (print .Template.BasePath "/etc/_secrets.conf.tpl") . | b64enc | indent 4 }}
