{{- range $appName, $appValues := .Values.apps }}
{{- if $appValues.enabled }}
{{- with $ }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netapp-harvest.fullname" . }}-{{ $appName }}-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "{{ include "netapp-harvest.fullname" . }}-{{ $appName }}-worker"
  template:
    metadata:
      annotations:
        configmap-hash: {{ include (print $.Template.BasePath "/configmap.yaml") . | replace .Chart.Version "0.1.5" | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/targets: storage
      labels:
        name: "{{ include "netapp-harvest.fullname" . }}-{{ $appName }}-worker"
    spec:
      containers:
        - name: poller
          image: {{ .Values.global.dockerHubMirror }}/{{ .Values.harvest.image.repository }}:{{ .Values.harvest.image.tag }}
          imagePullPolicy: {{ .Values.harvest.image.pullPolicy | default "IfNotPresent" }}
          command: ["sh", "start-poller.sh"]
          ports:
            - name: metrics
              containerPort: 13000
          resources:
            {{- toYaml .Values.harvest.resources | nindent 12 }}
          volumeMounts:
            - name: harvest-config
              subPath: start-poller.sh
              mountPath: /opt/harvest/start-poller.sh
            - name: harvest-config
              subPath: rest.limited.yaml
              mountPath: /opt/harvest/conf/rest/limited.yaml
            - name: harvest-config
              subPath: rest.custom_volume.yaml
              mountPath: /opt/harvest/conf/rest/9.12.0/custom_volume.yaml
            - name: harvest-config
              subPath: rest.iscsi_session.yaml
              mountPath: /opt/harvest/conf/rest/9.6.0/iscsi_session.yaml
            - name: harvest-config 
              mountPath: /opt/harvest/conf/restperf/limited.yaml
              subPath: restperf.limited.yaml
            - name: shared
              mountPath: /opt/harvest/shared
        - name: netappsd-worker
          image: {{ .Values.global.registry }}/{{ .Values.netappsd.image.repository }}:{{ .Values.netappsd.image.tag }}
          imagePullPolicy: {{ .Values.netappsd.image.pullPolicy | default "IfNotPresent" }}
          command: ["/app/netappsd", "worker"]
          args:
            - --master-url
            - http://{{ include "netapp-harvest.fullname" . }}-{{ $appName }}-master.{{ .Release.Namespace }}.svc:8000
            - --template-file
            - /app/harvest.yaml.tpl
            - --output-path
            - /app/shared
          env:
            - name: NETAPP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "netapp-harvest.fullname" . }}
                  key: netappUsername
            - name: NETAPP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "netapp-harvest.fullname" . }}
                  key: netappPassword
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            {{- toYaml .Values.harvest.resources | nindent 12 }}
          volumeMounts:
            - name: harvest-config
              mountPath: /app/harvest.yaml.tpl
              subPath: harvest.yaml.tpl
            - name: shared
              mountPath: /app/shared
      volumes:
        - name: harvest-config
          configMap:
            name: {{ include "netapp-harvest.fullname" . }}
        - name: shared
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "netapp-harvest.fullname" . }}-{{ $appName }}-master
spec:
  selector:
    matchLabels:
      name: {{ include "netapp-harvest.fullname" . }}-{{ $appName }}-master
  replicas: 1
  template:
    metadata:
      annotations:
        configmap-hash: {{ include (print $.Template.BasePath "/configmap.yaml") . | replace .Chart.Version "0.1.5" | sha256sum }}
      labels:
        name: {{ include "netapp-harvest.fullname" . }}-{{ $appName }}-master
    spec:
      containers:
        - name:  netappsd
          image: {{ .Values.global.registry }}/{{ .Values.netappsd.image.repository }}:{{ .Values.netappsd.image.tag }}
          imagePullPolicy: {{ .Values.netappsd.image.pullPolicy | default "IfNotPresent" }}
          command: ["/app/netappsd", "master"]
          args:
            - --region
            - {{ .Values.global.region }}
            - --tag
            - {{ $appName }}
            - --listen-addr
            - 0.0.0.0:8000
            - --worker
            - {{ include "netapp-harvest.fullname" . }}-{{ $appName }}-worker
          env:
            - name: NETAPP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "netapp-harvest.fullname" . }}
                  key: netappUsername
            - name: NETAPP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "netapp-harvest.fullname" . }}
                  key: netappPassword
            - name: NETBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "netapp-harvest.fullname" . }}
                  key: netboxToken
            - name: NETBOX_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "netapp-harvest.fullname" . }}
                  key: netboxHost
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8000
---
{{- end }}
{{- end }}
{{- end }}