apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    system: openstack
    application: {{ .Release.Name }}
type: Opaque
data:
  server_secrets: |
    {{ include (print .Template.BasePath "/etc/_server_secrets.tpl") . | b64enc | indent 4 }}
  server_agent_shared_secrets: |
    {{ include (print .Template.BasePath "/etc/_server_agent_shared_secrets.tpl") . | b64enc | indent 4 }}
