{{- if and (.Capabilities.APIVersions.Has "vcenter-operator.stable.sap.cc/v1") (contains ",nsxv3" .Values.ml2_mechanismdrivers ) }}
apiVersion: vcenter-operator.stable.sap.cc/v1
kind: VCenterTemplate
metadata:
  name: 'neutron-ml2-nsxv3-secret'
options:
  scope: 'cluster'
  jinja2_options:
    variable_start_string: '{='
    variable_end_string: '=}'
template: |
  apiVersion: v1
  kind: Secret
  metadata:
    name: neutron-ml2-nsxv3-{= name =}
    labels:
      system: openstack
      type: configuration
      component: neutron
      vcenter: {= host =}
      datacenter: {= availability_zone =}
      vccluster: {= cluster_name =}
  data:
    NSXV3_LOGIN_USER: {{ osapinsxt | b64enc }}
    {%- set bb = name | replace( "bb", "") | int %}
    {%- set hostname = "nsx-ctl-" + "bb" + ( '%03d' % bb ) + "." + domain %}
    NSXV3_LOGIN_PASSWORD = {{ {= username | derive_password(hostname) | quote =} | b64enc }}
{{ end }}
