---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: percona-xtradb-cluster-operator
  labels:
    app.kubernetes.io/component: percona-xtradb-cluster-operator
    app.kubernetes.io/name: percona-xtradb-cluster-operator
    app.kubernetes.io/managed-by: Helm
subjects:
- kind: ServiceAccount
  name: percona-xtradb-cluster-operator
  namespace: pxc-operator
roleRef:
  kind: ClusterRole
  name: percona-xtradb-cluster-operator
  apiGroup: rbac.authorization.k8s.io
