apiVersion: v1
kind: Secret
metadata:
  name: hermes-api
  namespace: hermes
labels:
  app: hermes-api
data:
  HERMES_OS_PASSWORD: {{ .Values.hermes.password | b64enc }}
{{- if and .Values.hermes.certs .Values.hermes.certs.tls_crt }}
{{ $config := .Values.hermes.certs }}
  tls.crt: {{ b64enc $config.tls_crt }}
  tls.key: {{ b64enc $config.tls_key }}
{{- end }}
