{{ if .Values.radosgw.dnsRewriteEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernikus.cloud.sap/skip-manage: "true"
data:
  Corefile: |
    .:53 {
      errors
      health
      {{- range .Values.radosgw.rewrites }}
      rewrite name {{ .from }} {{ .to }}
      {{- end }}
      kubernetes {{ .Values.radosgw.clusterDomain | default "cluster.local" }} in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
      }
      prometheus :9153
      forward . /etc/resolv.conf
      cache 30
      loop
      reload
      loadbalance
    }
{{- end }}
