ownerinfo:
  enabled: true

pxcoperator:
  enabled: true
  image: keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/percona/percona-xtradb-cluster-operator:1.15.0
  crVersion: 1.15.0
  watchNamespace: keystone-pxc
  disableTelemetry: true
  unsafeFlags:
    tls: true
  tls:
    enabled: false

owner-info:
  helm-chart-url: 'https://github.com/sapcc/helm-charts/tree/master/common/percona-operator'
  maintainers:
    - Birk Bohne
    - Vlad Gusev
  support-group: shared-services
  service: percona-operator