---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argora
  namespace: default
subjects:
  - kind: ServiceAccount
    name: argora
    namespace: default
roleRef:
    kind: ClusterRole
    name: argora
    apiGroup: rbac.authorization.k8s.io