{{- if .Values.nanny_enabled }}
{{- $ignore := required "missing list of bind servers in .Values.designate_nanny.cleaner.instances" .Values.designate_nanny.cleaner -}}
{{- $instances := required "missing list of bind servers in .Values.designate_nanny.cleaner.instances" .Values.designate_nanny.cleaner.instances -}}
{{ $top := . -}}
{{- range $instance := $instances }}
---
#  Deployment for cleaner instance on  {{ $instance }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $top.Release.Name }}-{{ $instance }}
data:
  nanny.yaml: |
{{ toYaml $top.Values.designate_nanny.config | indent 4 }} 
{{- end }}
{{- end }}
