{{- if .Values.nanny_enabled }}
{{- required "missing list of bind servers in .Values.designate_nanny.cleaner.instances" .Values.designate_nanny.cleaner }}
{{- required "missing list of bind servers in .Values.designate_nanny.cleaner.instances" .Values.designate_nanny.cleaner.instances }}
{{- range $instance := .Values.designate_nanny.cleaner.instances}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ $instance }}-os-secret
  labels:
    ccloud/support-group: network-api
    system: openstack
    application: designate
data:
  designate_nanny_os_password: {{ required "set password in .Values.designate_nanny.credentials.designate_api.password" .Values.designate_nanny.credentials.designate_api.password | b64enc }}

{{- end }}
{{- end }}
