{{- if .Values.nanny_enabled }}
{{- $ignore := required "missing list of bind servers in .Values.designate_nanny.cleaner.instances" .Values.designate_nanny.cleaner -}}
{{- $instances := required "missing list of bind servers in .Values.designate_nanny.cleaner.instances" .Values.designate_nanny.cleaner.instances -}}
{{ $top := . -}}
{{- range $instance := $instances}}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ $top.Release.Name }}-{{ $instance }}-os-secret
  labels:
    ccloud/support-group: network-api
    system: openstack
    application: designate
data:
  designate_nanny_os_password: {{ required "set password in $top.Values.designate_nanny.credentials.designate_api.password" $top.Values.designate_nanny.credentials.designate_api.password | b64enc }}
 
{{- end }}
{{- end }}
