{{- if .Values.nanny_enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-os-secret
  labels:
    ccloud/support-group: network-api
    system: openstack
    application: designate
data:
  designate_nanny_os_password: {{ required "set password in .Values.designate_nanny.credentials.designate_api.password" .Values.designate_nanny.credentials.designate_api.password | b64enc }}

{{- end }}
