global:
  region: regionOne
  domain: evil.corp
  registry: keppel.regionOne.cloud
  dockerHubMirrorAlternateRegion: dockerhubmirror.example.com
  tld: regionOne.cloud

  masakari_service_password: verySecret
  dbBackupServicePassword: topSecret


imageVersion: myTag

mariadb:
  enabled: true
  backup:
    enabled: false
  backup_v2:
    enabled: false
