apps:
  apod:
    enabled: false
  cinder:
    enabled: false
  manila:
    enabled: false

harvest:
  image:
    repository: rahulguptajss/harvest
    tag: 22.11.1-1
  loglevel: 2
  promPort: 13000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

netappsd:
  image:
    repository: netappsd
    tag: v2-20240130092608
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
