{{- if and $.Values.mariadb.enabled (not $.Values.mariadboperator.enabled) }}
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: {{ $.Release.Namespace }}
spec:
{{ if .Values.image.repository }}  image: {{ .Values.image.repository }}{{ end }}
{{ if .Values.image.pullPolicy }}  imagePullPolicy: {{ .Values.image.pullPolicy }}{{ end }}

  rootPasswordSecretKeyRef:
    name: mariadb-root
    key: password
    generate: false

  username: mariadb
  passwordSecretKeyRef:
    name: mariadb-password
    key: password
    generate: false
  database: {{ .Values.mariadb.database }}

  storage:
    size: {{ .Values.mariadb.storage.size }}

  replicas: {{ .Values.replicas | default 1 | int }}
  replicasAllowEvenNumber: {{ .Values.replicasAllowEvenNumber | default false }}

  galera:
    enabled: true
    replicaThreads: 1
  {{ if .Values.image.agent }}  agent:
    {{ if .Values.image.agent.repository }}  image: {{ .Values.image.agent.repository }} {{ end }}
  {{ end }}
  {{- if .Values.image.initContainer }}  initContainer:
    {{ if .Values.image.initContainer.repository }}  image: {{ .Values.image.initContainer.repository }} {{- end }}
  {{ end }}

  service:
    type: {{ .Values.mariadb.service.type }}
  connection:
    secretName: mariadb-conn
    secretTemplate:
      key: dsn
  primaryService:
    type: ClusterIP
  primaryConnection:
    secretName: mariadb-conn-primary
    secretTemplate:
      key: dsn
  secondaryService:
    type: {{ .Values.mariadb.service.type }}
  secondaryConnection:
    secretName: mariadb-conn-secondary
    secretTemplate:
      key: dsn

  updateStrategy:
    type: ReplicasFirstPrimaryLast

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M

  metrics:
    passwordSecretKeyRef:
      name: mariadb-metrics
      key: password
      generate: false
    enabled: true
{{- end }}