{{- if and $.Values.mariadb.enabled (not $.Values.mariadboperator.enabled) }}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: root
  namespace: {{ $.Release.Namespace }}
spec:
  name: root
  mariaDbRef:
    name: root
  passwordSecretKeyRef:
    name: root
    key: password
  maxUserConnections: 0
  host: "localhost"
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: mariadb
  namespace: {{ $.Release.Namespace }}
spec:
  name: mariadb
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: mariadb
    key: password
  maxUserConnections: 20
  host: "%"
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: metrics
  namespace: {{ $.Release.Namespace }}
spec:
  name: metrics
  mariaDbRef:
    name: metrics
  passwordSecretKeyRef:
    name: metrics
    key: password
  maxUserConnections: 8
  host: "localhost"
{{- end }}