# iscsi_session with initiator and initiator_address as instance_keys

name:               ISCSISession
query:              api/protocols/san/iscsi/sessions
object:             iscsi_session

counters:
  - ^^connections.#.initiator_address.address => initiator_address
  - ^^initiator.name                          => initiator
  - ^svm.name                                 => svm
  - ^tsih                                     => tsih

collect_only_labels: true

export_options:
  instance_keys:
    - initiator
    - initiator_address
  instance_labels:
    - svm
    - tsih