apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-bin
  labels:
    app: {{ template "fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: rabbitmq
    {{- include "rabbitmq.labels" . | indent 4 }}
data:
  rabbitmq_setup_users.py: |
{{ .Files.Get "files/rabbitmq-setup-users.py" | indent 4 }}
  rabbitmq_configurator_readiness.py: |
{{ .Files.Get "files/rabbitmq-configurator-readiness.py" | indent 4 }}
