apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "promlens.fullname" . }}
  labels:
    {{- include "promlens.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "promlens.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "promlens.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "promlens.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
            {{- if .Values.config.grafana.enabled }}
            - --grafana.api-token-file=/var/grafana-secret/api-token
            {{- if .Values.config.grafana.defaultDatasourceId }}
            - --grafana.default-datasource-id={{ .Values.config.grafana.defaultDatasourceId }}
            {{- end }}
            - --grafana.url={{ .Values.config.grafana.url }}
            {{- end }}
            - --log.level={{ .Values.config.log.level }}
            - --log.format={{ .Values.config.log.format }}
            {{- if and (.Values.config.sharedLinks.sql.enabled) (not .Values.config.sharedLinks.sql.createTables) }}
            - --no-shared-links.sql.create-tables
            {{- end }}
            {{- if .Values.config.sharedLinks.gcs.enabled }}
            - --shared-links.gcs.bucket={{ .Values.config.sharedLinks.gcs.bucket }}
            {{- end }}
            {{- if .Values.config.sharedLinks.sql.enabled }}
            - --shared-links.sql.driver={{ .Values.config.sharedLinks.sql.driver }}
            - --shared-links.sql.retention={{ .Values.config.sharedLinks.sql.retention }}
            {{- end }}
            {{- if.Values.config.web.defaultPrometheusUrl }}
            - --web.default-prometheus-url={{ .Values.config.web.defaultPrometheusUrl }}
            {{- end }}
            {{- if.Values.config.web.externalUrl }}
            - --web.external-url={{ .Values.config.web.externalUrl }}
            {{- end }}
            {{- if.Values.config.web.routePrefix }}
            - --web.route-prefix={{ .Values.config.web.routePrefix }}
            {{- end }}
          {{- if or (.Values.config.sharedLinks.gcs.enabled) (.Values.config.sharedLinks.sql.enabled) }}
          env:
            {{- if .Values.config.sharedLinks.gcs.enabled }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/gcs-secret/gcs-cred.json
            {{- end }}
            {{- if .Values.config.sharedLinks.sql.enabled }}
            - name: PROMLENS_SHARED_LINKS_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "promlens.sql.secretName" . }}
                  key: dsn
            {{- end }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or (.Values.config.grafana.enabled) (.Values.config.sharedLinks.gcs.enabled) }}
          volumeMounts:
            {{- if .Values.config.grafana.enabled }}
            - mountPath: /var/grafana-secret
              name: grafana-secret
            {{- end }}
            {{- if .Values.config.sharedLinks.gcs.enabled }}
            - mountPath: /var/gcs-secret
              name: gcs-secret
            {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or (.Values.config.grafana.enabled) (.Values.config.sharedLinks.gcs.enabled) }}
      volumes:
        {{- if .Values.config.grafana.enabled }}
        - name: grafana-secret
          secret:
            defaultMode: 420
            secretName: {{ include "promlens.grafana.secretName" . }}
        {{- end }}
        {{- if .Values.config.sharedLinks.gcs.enabled }}
        - name: gcs-secret
          secret:
            defaultMode: 420
            secretName: {{ include "promlens.gcs.secretName" . }}
        {{- end }}
      {{- end }}
