{{- if and (.Values.config.sharedLinks.gcs.enabled) (not .Values.config.sharedLinks.gcs.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "promlens.gcs.secretName" . }}
  labels:
    {{- include "promlens.labels" . | nindent 4 }}
data:
  gcs-cred.json: |
    {{ .Values.config.sharedLinks.gcs.storageAccount | b64enc }}
{{- end }}
