{{- if and (.Values.config.grafana.enabled) (not .Values.config.grafana.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "promlens.grafana.secretName" . }}
  labels:
    {{- include "promlens.labels" . | nindent 4 }}
data:
  api-token: {{ .Values.config.grafana.apiToken | b64enc }}
{{- end }}
