{{- if and (.Values.config.sharedLinks.sql.enabled) (not .Values.config.sharedLinks.sql.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "promlens.sql.secretName" . }}
  labels:
    {{- include "promlens.labels" . | nindent 4 }}
data:
  dsn: {{ .Values.config.sharedLinks.sql.dsn | b64enc }}
{{- end }}
